global using OneCore.Collections;
global using OneCore.Comparers;
global using OneCore.Extensions;
global using OneCore.ModelPatch.Extensions;
global using OneCore.ModelPatch.Models;
global using OneCore.Models;
global using OneCore.Reflection;
global using OneCore.Results;
global using OneCore.Services;
global using System.Collections;
global using System.ComponentModel.DataAnnotations;
global using System.Linq.Expressions;
global using System.Reflection;
global using ReferenceEqualityComparer = OneCore.Comparers.ReferenceEqualityComparer;