name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target-framework:
          - net9.0
          - net10.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            10.0.x

      - name: Restore solution
        run: dotnet restore CoreOne.ModelPatch.sln

      - name: Build solution
        run: dotnet build CoreOne.ModelPatch.sln --configuration Release --framework ${{ matrix.target-framework }} --no-restore

      - name: Test solution
        run: dotnet test CoreOne.ModelPatch.sln --configuration Release --framework ${{ matrix.target-framework }} --no-build

  pack:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            10.0.x

      - name: Restore solution
        run: dotnet restore CoreOne.ModelPatch.sln

      - name: Pack library
        run: dotnet pack src/CoreOne.ModelPatch/CoreOne.ModelPatch.csproj --configuration Release --no-restore